# 用户头像与昵称
avatar:
  author_photo: /images/avatar.png
  author_nickname: Hawthorn
  path: /

# 友链详细信息：支持多个友链
friends:
  -
    nickname: Yanko
    site: https://evergarden.ink/
    meta:

# 文章搜索
search:
  enable: false

# 文章分享
postShare:
  enable: false
